# 服务器配置
server:
  mode: "debug" # 可选值: debug, release
  port: 8080
  swag: true

# 数据库配置
database:
  host: "localhost" #localhost
  port: 3306
  username: "root" #postgres
  password: "123456" #123456
  dbname: "hserp"
  dialect: "mysql"
  max_open_conns: 20 # 最大打开连接数
  max_idle_conns: 5 # 最大空闲连接数
  max_lifetime: 60 # 单位: 分钟

# 运行时数据目录配置
runtime:
  dir: "./runtime" # 运行时数据根目录，日志存放在 {dir}/logs，黑名单存放在 {dir}/blacklist.json

# 日志配置，严格大小写
log:
  level: "Info" # 日志级别:  Error, Warn, Info
  access: true # 是记录访问日志
  level_sql: "Info" # SQL日志级别: Silent, Error, Warn, Info
  
website:
  dir: "./public" # 网站根目录
  upload_url: "/upload" # 上传文件保存目录 相对public
  upload_temp_url: "/upload/temp"  # 临时文件目录 相对public


# JWT配置
jwt:
  secret: "cyp_secret_key"
  expiry: 24 # 小时

# 自动迁移配置 (默认为false)
auto_migrate: true
# 自动同步RBAC权限点 (默认为false)
auto_rbac_point: false
# 超级管理员账号
super_account: "super"